[package]
name = "discord_bot"
version = "0.1.0"
authors = ["Matt Woelk <matt@mattwoelk.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord = {git = "https://github.com/tinaun/discord-rs", branch = "async_internals", default-features = false }
color-backtrace = "0.3"
